### ISSUE TITLE
Jekyll serve issue when I'm going to start project

### ISSUE THREAD

**Issue by CarMoreno** [YJPL/soon#1]
Hi, I've Jekyll 3.1.6, I cloned your repo and when I execute jekyll serve command, I get the following error:

```
Configuration file: /opt/lampp/htdocs/soon/_config.yaml
       Deprecation: The 'plugins' configurationoption has been renamed to 'plugins_dir'. Please update your config file accordingly.
            Source: /opt/lampp/htdocs/soon
       Destination: /opt/lampp/htdocs/soon/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
      Invalid Date: '' is not a valid datetime.
  Liquid Exception: exit in _layouts/post.html
```
So, Can you fix this issue?

Thank you.

**Comment by YJPL** [comment]
Hello,

> So, Can you fix this issue?

I removed the post sample that was creating this issue in some older Jekyll versions. Also removed specific version in `Gemfile`. It should work for you in Jekyll 3.1.6 now. Let me know.

**Comment by CarMoreno** [comment]
Thank you!! Right now it's working!
